name: Build Alpha Engine EXE
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Обновлено до v4
      
      - name: Setup Python
        uses: actions/setup-python@v5 # Обновлено до v5
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install customtkinter gpt4all pyinstaller ddgs pyautogui
          
      - name: Compile EXE
        run: |
          # Собираем всё в один файл (--onefile)
          pyinstaller --noconsole --onefile --name "AlphaEngine_v1" engine.py
          
      - name: Upload Finished EXE
        uses: actions/upload-artifact@v4 # ФИКС ОШИБКИ: Теперь v4
        with:
          name: AlphaEngine_Windows_Build
          path: dist/AlphaEngine_v1.exe
          retention-days: 5
